# Configuration for git-changelog (https://github.com/aldrin/git-changelog)
conventions:
  categories:
    - {tag: "break", title: "Breaking Changes"}
    - {tag: "feature", title: "Features"}
    - {tag: "fix", title: "Fixes"}
    - {tag: "", title: "Notes"}
    - {tag: "add", title: "Additions"}
    - {tag: "remove", title: "Removals"}
    - {tag: "deprecate", title: "Deprecations"}
  scopes:
    - {tag: "", title: ""}
    - {tag: "doc", title: "Documentation"}
    - {tag: "infra", title: "Infrastructure"}
output:
  post_processors:
    - {lookup: "GH-(?P<id>\\d+)", replace: "[GH-$id](https://github.com/jorgenpt/bichrome/issues/$id)"}
    - {lookup: "#(?P<id>\\d+)", replace: "[GH-$id](https://github.com/jorgenpt/bichrome/issues/$id)"}
